sequenceDiagram
participant User
participant API
participant BusinessLogic
participant Database

User->>API: Register user
API->>BusinessLogic: Validate user registeration
BusinessLogic->>Database: Save User
Database-->>BusinessLogic: User saved
BusinessLogic-->>API: Return Response
API-->>User: Registeration Success/Failure

User->>API: Create place
API->>BusinessLogic: Validate user auth and place creation
BusinessLogic->>Database: Save Place
Database-->>BusinessLogic: Place saved
BusinessLogic-->>API: Return Response
API-->>User: Place creation Success/Failure

User->>API: Submit place review
API->>BusinessLogic: Validate user auth place review
BusinessLogic->>Database: Save place review
Database-->>BusinessLogic: Place review saved
BusinessLogic-->>API: Return Response
API-->>User: Place review Success/Failure

User->>API: Fetching a List of Places
API->>BusinessLogic: Validate user auth and filters
BusinessLogic->>Database: Fetch places with filters and limit
Database-->>BusinessLogic: Row places data
BusinessLogic-->>API: Convert row object to JSON
API-->>User: Return the places list (json)
